Downloading reviewer folder to reference

diff --git a/.github/workflows/ai-code-review.yaml b/.github/workflows/ai-code-review.yaml
--- a/.github/workflows/ai-code-review.yaml
+++ b/.github/workflows/ai-code-review.yaml
@@ -64,36 +64,48 @@ jobs:
           git fetch origin $BASE
           git fetch origin $HEAD
 
-          terraform_changed_files=$(git diff --diff-filter=ACMR --name-only origin/$BASE...origin/$HEAD "infrastructure/**" | grep '\.tf$' || true)
+          # ---------------- Terraform ----------------
+          terraform_changed_files=$(git diff --diff-filter=ACMR --name-only origin/$BASE...origin/$HEAD "**" | grep '\.tf$' || true)
           if [ -n "$terraform_changed_files" ]; then
-            mkdir -p reviewer/terraform_context
+            echo "terraform files changed: $terraform_changed_files"
+            mkdir -p src/reviewer/terraform_context
+            
             for file in $terraform_changed_files; do
-              mkdir -p "reviewer/terraform_context/$(dirname "$file")"
-              echo "filename: $file" > "reviewer/terraform_context/$file"
-              cat "$file" >> "reviewer/terraform_context/$file" || echo "Failed to append contents of $file"
+              mkdir -p "src/reviewer/terraform_context/$(dirname "$file")"
+              echo "filename: $file" > "src/reviewer/terraform_context/$file"
+              cat "$file" >> "src/reviewer/terraform_context/$file" || echo "Failed to append contents of $file"
             done
-            find reviewer/terraform_context -type f -exec split -b 200000 {} {}_split_ \;
-            cd reviewer
+            find src/reviewer/terraform_context -type f -exec split -b 200000 {} {}_split_ \;
+            cd src/reviewer
             poetry export --without-hashes -o requirements.txt
             pip install -r requirements.txt
-            cd ..
-            find reviewer/terraform_context -type f -name "*_split_*" | xargs -I {} -n 1 -P 8 python3 reviewer/function.py --filename {} --review-type infrastructure >> reviewer/llm-terraform.txt
+            cd ../..
+            find src/reviewer/terraform_context -type f -name "*_split_*" | xargs -I {} -n 1 -P 8 python3 src/reviewer/function.py --filename {} --review-type infrastructure >> src/reviewer/llm-terraform.txt
+          else
+            echo "No terraform files changed."
           fi
 
-          python_changed_files=$(git diff --diff-filter=ACMR --name-only origin/$BASE...origin/$HEAD "src/**" ':!src/examples/**' | grep '\.py$' || true)
+          # ---------------- Python ----------------
+          python_changed_files=$(git diff --diff-filter=ACMR --name-only origin/$BASE...origin/$HEAD \
+          "src/**" \
+          ':!src/examples/**' \
+          ':!src/reviewer/**' | grep '\.py$' || true)
           if [ -n "$python_changed_files" ]; then
-            mkdir -p reviewer/python_context
+            echo "python files changed: $python_changed_files"
+            mkdir -p src/reviewer/python_context
             for file in $python_changed_files; do
-              mkdir -p "reviewer/python_context/$(dirname "$file")"
-              echo "# filename: $file" > "reviewer/python_context/$file"
-              cat "$file" >> "reviewer/python_context/$file" || echo "Failed to append contents of $file"
+              mkdir -p "src/reviewer/python_context/$(dirname "$file")"
+              echo "# filename: $file" > "src/reviewer/python_context/$file"
+              cat "$file" >> "src/reviewer/python_context/$file" || echo "Failed to append contents of $file"
             done
-            find reviewer/python_context -type f -exec split -b 200000 {} {}_split_ \;
-            cd reviewer
+            find src/reviewer/python_context -type f -exec split -b 200000 {} {}_split_ \;
+            cd src/reviewer
             poetry export --without-hashes -o requirements.txt
             pip install -r requirements.txt
-            cd ..
-            find reviewer/python_context -type f -name "*_split_*" | xargs -I {} -n 1 -P 8 python3 reviewer/function.py --filename {} --review-type python >> reviewer/llm-python.txt
+            cd ../..
+            find src/reviewer/python_context -type f -name "*_split_*" | xargs -I {} -n 1 -P 8 python3 src/reviewer/function.py --filename {} --review-type python >> src/reviewer/llm-python.txt
+          else
+            echo "No python files changed."
           fi
 
       - name: Comment on PR with AI Reviews
